apiVersion: v1
kind: Service
metadata:
  name: {{ template "postal.fullname" . }}-external
spec:
  type: LoadBalancer
  selector:
    app: {{ template "postal.name" . }}
    component: postal
  ports:
  - name: web
    port: 80
    targetPort: web
    protocol: TCP

